# Generated by Django 2.0.7 on 2018-07-25 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('servicio', models.CharField(max_length=255)),
                ('ciudad', models.CharField(max_length=255)),
                ('fecha', models.CharField(max_length=255)),
                ('total', models.IntegerField()),
            ],
        ),
    ]
